const MUTATION_TYPES = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_ACTIVE_COLOR: "SET_ACTIVE_COLOR",
  SET_MAPPING_TASK_AND_COLOR: "SET_ACTIVE_COLOR",
  //   TODO: 初回の主要データのfetch
};

export default MUTATION_TYPES;
